<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Weeklyschedule;
use App\Models\Monthlyschedule;

class MonthlySchedulesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function oneset(Monthlyschedule $monthly)
    {
        $data = [
                    //1st Week
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'Accounting',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ADMIN OFFICE',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'BUDGET OFFICE',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'CASHIER ADMIN',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'CHIEF OF CLINICS',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'FINANCE OFFICE',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'IASO',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'SECURITY OFFICE',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'RBC',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'IM OFFICE (TRAINING ROOM 7)',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    //2nd Week
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'OB OFFICE (TRAINING ROOM 5)',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'LEGAL OFFICE (TRAINING ROOM 6)',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'TRAINING',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PETRU',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PERSONNEL',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PROCUREMENT',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PROPERTY',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PROPERTY STOCKROOM',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'MEDICAL RECORD',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'CECAP',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    //3RD wEEK
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'DIETARY',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ENGINEERING',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'HOUSEKEEPING',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'LAUNDRY',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PHIC HOUSEKEEPING',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'DOH BOTIKA',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'CATHLAB',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'IHOMS',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'WARD 12',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'WARD 12 OPD-CBS',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    //4TH WEEK
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'LABORATORY',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PHIC MAIN OFFICE',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'CCU',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'CCU EXTENSION',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ICU',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'EMERGENCY COMPLEX',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ORTHOPEDICS OFFICE (ER DOWN)',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'HOLDING AREA ER',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PINK CENTER',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'REHAB',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'RTU',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],

                ];

        Weeklyschedule::insert($data);

        return redirect()->route('show.schedule', $monthly);
        // return back();
    }

    public function twoset(Monthlyschedule $monthly)
    {
        $data = [
                    //1st Week
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'MANAGEMENT SYSTEM UNIT',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'EMED OFFICE',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'SURGICAL ONCOLOGY',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ENT OFFICE',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ETHICS OFFICE',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'MEDICAL RECORD SATELLITE',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'MEDICAL SOCIAL WORKER',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'BILLING',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'CENTRAL STERILE SUPPLY',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'MALASAKIT',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    //2ND WEEK
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PHIC MAIN OFFICE',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'CASHIER MAIN BUILDING',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PHILHEALTH WARD',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'WARD 9',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ND GROUND FLOOR',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ND 2ND FLOOR',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ND 3RD FLOOR',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ND 4TH FLOOR',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ND EXTENSION',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'RADIOLOGY',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    //3rd week
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'LABOR ROOM',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'OB-OR',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'NEWBORN',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'NICU',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'NICU ILI',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'RENAL',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'SHOCKWAVE',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'UROLOGY',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'WARD 10 ADULT',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'WARD 10 PEDIA',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'EREID UNIT',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    //4thweek
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ADMITTING LRU',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'BILLING LRU',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'MSW LRU',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'LABOR ROOM EXTENSION',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'WARD 7 GROUND FLOOR',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'WARD 7 2ND FLOOR',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'WARD 7 3RD FLOOR',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PEDIA OFFICE',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'WARD 1 HRU',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'WARD 1 LRU',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'WARD 2',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PHIC ANNEX B',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],

                ];

        Weeklyschedule::insert($data);

        return redirect()->route('show.schedule', $monthly);
        // return back();
    }


    public function threeset(Monthlyschedule $monthly)
    {
        $data = [
                    //1st Week
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ICC',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'KAAMBAG',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'KMC UNIT',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'SP GROUND FLOOR',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'SP 2ND FLOOR',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'SP 3RD FLOOR',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'GENERAL SURGERY LIBRARY',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ANESTESIA OFFICE',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'OPERATING ROOM',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'OR CUSTODIAN',
                        'weekly' => '1week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    //2ND WEEK
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PACU 1ST FLOOR',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PACU 2ND FLOOR',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'CENTRAL STERILE SUPPLY',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'CHIEF OF HOSPITAL',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'CHIEF OF NURSE',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'INFORMATION',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'OSM',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'LEGAL',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ADMITTING',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PHARMACY ER',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PHARMACY MAIN',
                        'weekly' => '2week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    //3RD WEEK
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PHARMACY OR',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'NEUROSURGICAL OFFICE',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'WARD 11',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PHIC ANNEX A',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ANIMAL BITE',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'CASHIER OPD',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'CHILD SURVIVAL',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ECG / EEG',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'ENDOSCOPY',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'EYE CENTER',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'EYE CENTER OR',
                        'weekly' => '3week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    //4TH WEEK
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'FAMED OFFICE',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'LABORATORY OPD',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PHILHEALTH OPD',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'MEDICAL RECORD OPD',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'OPTHA OFFICE',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'PHU',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'STATION 1',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'STATION 2',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'STATION 3',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'STATION 4',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],
                    [
                        'monthlyschedule_id' => $monthly->id,
                        'department_name' => 'WELLNESS',
                        'weekly' => '4week',
                        'partial' => null,
                        'done' => null,
                        'actual' => null,
                    ],

                ];

        Weeklyschedule::insert($data);

        return redirect()->route('show.schedule', $monthly);
        // return back();
    }

    public function storesched(Monthlyschedule $weeklydata)
    {
        $monthly = Weeklyschedule::create([
            'department_name' => request('department_name'),
            'weekly' => request('weekly'),
            'partial' => null,
            'done' => null,
            'actual' => null,
            'monthlyschedule_id' => $weeklydata->id
        ]);

        return back();
    }
}
